export const ActionType = {
  GET_GLOBAL_MARKET_INFORMATION: `GET_GLOBAL_MARKET_INFORMATION`,
  IS_GLOBAL_MARKET_INFORMATION_LOADING: `IS_GLOBAL_MARKET_INFORMATION_LOADING`,
  GET_COINS_DATA: `GET_COINS_DATA`,
  IS_COINS_DATA_LOADING: `IS_COINS_DATA_LOADING`,
  ON_PREV_BUTTON_CLICK: `ON_PREV_BUTTON_CLICK`,
  ON_NEXT_BUTTON_CLICK: `ON_NEXT_BUTTON_CLICK`,
  GET_FILTERED_COINS_DATA: `GET_FILTERED_COINS_DATA`,
  SET_FILTERED_COINS_DATA_TO_EMPTY: `SET_FILTERED_COINS_DATA_TO_EMPTY`,
  IS_ERROR: `IS_ERROR`,
  SET_ACTIVE_INDEX: `SET_ACTIVE_INDEX`,
};
